### PR TITLE
Added page for New 3DS XL

### LINKED ISSUE #16: Nintendo New 3DS XL
Would you be interested in a separate entry for the "New 3DS XL"?

I don't think there's much difference but I know they are more powerful and with a slightly different button layout.

### PR DESCRIPTION
**Pull request by AverageMarcus**
Fixes #16 

Added details of the New 3DS XL as it has a new version of the NetFront browser.

Still requires an image for the console. If you have any template from the 3DS XL I'd be happy to take a stab at it.

### CODE REVIEW

**Comment by maban** [comment]
Oooh, thank you! I'll take a look!

**Comment by AverageMarcus** [comment]
This PR is still missing the image for the console. (`/device/new3dsxl/new3dsxl-controller.png`).

It's slightly different to the old 3DS XL. Some buttons have moved, the volume slider is opposite the 3D slider and there is a new thumb control on the right.

See: http://console.maban.co.uk/device/new3dsxl/New3DSXL-Front.jpg

**Comment by maban** [comment]
Ahh, I just added one with the new c-stick but I do need to update it more with the home button and new labels. It's just going to take a bit longer because the diagram I based it off is saved as a Fireworks png which isn't editable in Sketch, and I need to convert all of them to SVGs anyway.

**Comment by AverageMarcus** [comment]
I've hacked together a bit more on the image. It's not perfect as its still missing the stuff on the bottom (stylus, card slot etc.)

Not sure if you want to use of not :smile: 

new3dsxl

**Comment by maban** [comment]
Haha! Nice, thank you! I'll pop it in :)

**Pull request merged**
